// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApPJEq2yu1FIHdMpdSMjaTQChKqZkEX3A',
    appId: '1:829298540112:web:8b6c8984d1c95076ffdb55',
    messagingSenderId: '829298540112',
    projectId: 'flutter-maps-d6a2e',
    authDomain: 'flutter-maps-d6a2e.firebaseapp.com',
    storageBucket: 'flutter-maps-d6a2e.appspot.com',
    measurementId: 'G-62NMCN1RNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAuD-Ewp5x4TQ5Hivrd1qzQJ0SeHBN2aM',
    appId: '1:829298540112:android:90cbb32cbd260332ffdb55',
    messagingSenderId: '829298540112',
    projectId: 'flutter-maps-d6a2e',
    storageBucket: 'flutter-maps-d6a2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7M_2YqmqeblY_Z9lghlptPDRDFC6_1Tc',
    appId: '1:829298540112:ios:c4416ab484bd7b84ffdb55',
    messagingSenderId: '829298540112',
    projectId: 'flutter-maps-d6a2e',
    storageBucket: 'flutter-maps-d6a2e.appspot.com',
    androidClientId: '829298540112-nc499f2ukmtart6gg028ibmolml0598e.apps.googleusercontent.com',
    iosClientId: '829298540112-n06ev3e04lo7uit7b6mu9tt5ukj2nra4.apps.googleusercontent.com',
    iosBundleId: 'com.example.sweatSmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApPJEq2yu1FIHdMpdSMjaTQChKqZkEX3A',
    appId: '1:829298540112:web:a6a64edcda533620ffdb55',
    messagingSenderId: '829298540112',
    projectId: 'flutter-maps-d6a2e',
    authDomain: 'flutter-maps-d6a2e.firebaseapp.com',
    storageBucket: 'flutter-maps-d6a2e.appspot.com',
    measurementId: 'G-4HF4R0H7E9',
  );
}
