name: Android Fastlane With Firebase App Distribution # Optional: Workflow Name 

 
on:    
  push: 
    branches: 
      - main 
jobs:   # Groups together all the jobs that run in this workflow. 
  distribute_to_firebase:  # Job Name
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4  

      - name: Setup JDK 17   
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin' 
 
  
      - name: Install Flutter  
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

              
      - name: Setup Ruby 
        uses: ruby/setup-ruby@v1 
        with: 
          ruby-version: 3.3.4 
          bundler-cache: true   
          working-directory: android   

      - name: Build and Distribute App
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
         
        run: |
          bundle exec fastlane android firebase_distribution
        working-directory: android 
       